### ISSUE TITLE
 DLL load failed while importing ujson: 找不到指定的模块

### ISSUE THREAD

**Issue by namewasher** [Cvandia/nonebot_plugin_genshin_cos#12]
报错

**怎么出现的**
1.直接安装后运行

**异常情况**
10-24 13:12:35 [ERROR] nonebot | Failed to import "nonebot_plugin_genshin_cos"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Users\Administrator\Desktop\1\liu\.venv\Lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\1\liu\.venv\Lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\1\liu\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\1\liu\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\1\liu\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Administrator\Desktop\1\liu\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\1\liu\.venv\Lib\site-packages\nonebot_plugin_genshin_cos\__init__.py", line 23, in <module>
    import ujson as json
ImportError: DLL load failed while importing ujson: 找不到指定的模块。

**屏幕截图**

![屏幕截图(1)](https://github.com/Cvandia/nonebot_plugin_genshin_cos/assets/135351832/787289d6-f870-46a9-b934-4cc149c4acf7)

**版本情况**
python:3.11.4
nb-cli:1.2.5
pip:23.3.1
……

**额外的说明**
这里是额外的描述

**Comment by Cvandia** [comment]
明白

**Comment by namewasher** [comment]
没问题了，我安装了c++和net.framework,之后就不报错了
