### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 65658dsf** [Cvandia/nonebot_plugin_genshin_cos#15]
**描述bug**
1.安装后启动直接报错

**怎么出现的**
1.安装后启动直接报错
……

**异常情况**
07-06 20:44:58 [ERROR] nonebot | Failed to import "nonebot_plugin_genshin_cos"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "E:\frpbot\.venv\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "E:\frpbot\.venv\lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "E:\frpbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "E:\frpbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "E:\frpbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "E:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "E:\frpbot\.venv\lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\frpbot\.venv\lib\site-packages\nonebot_plugin_genshin_cos\__init__.py", line 15, in <module>
    import ujson as json
ImportError: DLL load failed while importing ujson: 找不到指定的模块

**屏幕截图**
无

**版本情况**
python:3.12
nb-cli:最新
pip:24.1.1
……

**额外的说明**
这里是额外的描述

**Comment by Cvandia** [comment]
1. 确认 ujson 是否已正确安装：
你可能需要重新安装 ujson。在你的命令行工具中，尝试以下命令来安装或重新安装 ujson：
```
bash

pip install --upgrade pip
pip install --upgrade ujson
```
2.
尝试使用其他 JSON 库：
如果 ujson 始终无法正常工作，你可以考虑使用 Python 标准库中的 json 模块，或者另一个像 orjson 这样的库，它们可能不需要额外的 DLL 文件。

3.如果你的系统是多架构的（如 32 位和 64 位混合），确保你安装的 Python 和所有库都是针对相同架构的。
